# Generated by Django 4.1.4 on 2022-12-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailconfirm'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailconfirm',
            table='email_confirm',
        ),
    ]
