# Generated by Django 4.1.4 on 2022-12-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_emailconfirm_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirm',
        ),
    ]
