# Generated by Django 4.1.4 on 2022-12-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='slug',
        ),
    ]
