# Generated by Django 4.1.4 on 2023-01-05 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Project', max_length=100)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('release_date', models.DateTimeField()),
                ('approved', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.AddIndex(
            model_name='projects',
            index=models.Index(fields=['name'], name='name_projects_index'),
        ),
    ]
