# Generated by Django 4.1.4 on 2023-01-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='release_date',
        ),
    ]
